app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
article:
    type:     rest
    resource: AppBundle\Controller\ArticleController
client:
    type:     rest
    resource: AppBundle\Controller\ClientController