app_basket:
    resource: "@AppBundle/Controller/BasketController.php"
    type:     annotation

app_commande:
    resource: "@AppBundle/Controller/CommandeController.php"
    type:     annotation

app_location:
    resource: "@AppBundle/Controller/LocationController.php"
    type:     annotation

app_categorie:
    resource: "@AppBundle/Controller/CategorieController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation
article:
    type:     rest
    resource: AppBundle\Controller\ArticleController
client:
    type:     rest
    resource: AppBundle\Controller\ClientController
categorie:
    type:     rest
    resource: AppBundle\Controller\CategorieController
location:
    type:     rest
    resource: AppBundle\Controller\LocationController
commande:
    type:     rest
    resource: AppBundle\Controller\CommandeController
basket:
    type:     rest
    resource: AppBundle\Controller\BasketController