AppBundle\Entity\Client:
    attributes:
        id:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']
        name:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']
        lastname:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']
        email:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']
        birthdate:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']  
        sex:
            groups: ['client', 'location', 'commande', 'basket', 'article',
             'preparateur', 'auth-token']
        commandes:
            groups: ['client', 'location', 'auth-token']
        basket_parent:
            groups: ['client', 'location', 'auth-token']
        locations:
            groups: ['client', 'preparateur', 'auth-token']


AppBundle\Entity\Location:
    attributes:
        id:
            groups: ['client', 'location', 'preparateur', 'auth-token']
        adress:
            groups: ['client', 'location', 'preparateur', 'auth-token']
        city:
            groups: ['client', 'location', 'preparateur', 'auth-token']
        codePostale:
            groups: ['client', 'location', 'preparateur', 'auth-token']
        tel:
            groups: ['client', 'location', 'preparateur', 'auth-token']
        client:
            groups: ['location']


AppBundle\Entity\Article:
    attributes:
        id:
            groups: ['article', 'categorie', 'client', 'commande', 'basket',
             'preparateur', 'auth-token']
        name:
            groups: ['article', 'categorie', 'client', 'commande', 'preparateur',
             'auth-token']
        description:
            groups: ['article', 'categorie', 'client', 'commande', 'preparateur',
             'auth-token']
        price:
            groups: ['article', 'categorie', 'client', 'commande', 'preparateur',
             'auth-token']
        img:
            groups: ['article', 'categorie', 'client', 'commande', 'preparateur',
             'auth-token']
        marque:
            groups: ['article', 'categorie', 'client', 'commande', 'preparateur',
             'auth-token']
        categories:
            groups: ['article', 'client', 'commande', 'preparateur', 'auth-token']
        basket:
            groups: ['article']  

AppBundle\Entity\Categorie:
    attributes:
        name:
            groups: ['categorie', 'article', 'client', 'commande', 'basket', 'preparateur',
             'auth-token'] 
        articles:
            groups: ['categorie'] 

AppBundle\Entity\Basket:
    attributes:
        id:
            groups: ['client', 'basket', 'commande', 'article', 'auth-token']
        price:
            groups: ['client', 'basket', 'commande', 'article', 'auth-token'] 
        delivry:
            groups: ['client', 'basket', 'commande', 'article', 'auth-token']
        articles:
            groups: ['client', 'basket', 'commande','preparateur', 'auth-token']
        client_parent:
            groups: ['basket', 'commande', 'article', 'preparateur'] 

AppBundle\Entity\Commande:
    attributes:
        id:
            groups: ['client', 'article', 'commande', 'auth-token']
        client:
            groups: ['commande', 'preparateur']
        articles:
            groups: ['commande', 'client', 'preparateur']
        preparateur:
            groups: ['commande', 'auth-token']
        treatment:
            groups: ['commande', 'client', 'preparateur', 'auth-token']
        inDelivring:
            groups: ['commande', 'client', 'preparateur', 'auth-token']

AppBundle\Entity\Preparateur:
    attributes:
        id:
            groups: ['preparateur']
        name:
            groups: ['preparateur', 'commande']
        mdp:
            groups: ['preparateur']
        commandes:
            groups: ['preparateur']

AppBundle\Entity\AuthToken:
    attributes:
        id:
            groups: ['auth-token']
        value:
            groups: ['auth-token']
        createdAt:
            groups: ['auth-token']
        client:
            groups: ['auth-token']