AppBundle\Entity\Client:
    attributes:
        id:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        name:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        mdp:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        lastname:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        email:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        birthdate:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']  
        sex:
            groups: ['client', 'location', 'commande', 'basket', 'article', 'preparateur']
        commandes:
            groups: ['client', 'location']
        basket_parent:
            groups: ['client', 'location']
        locations:
            groups: ['client', 'preparateur']


AppBundle\Entity\Location:
    attributes:
        id:
            groups: ['client', 'location', 'preparateur']
        adress:
            groups: ['client', 'location', 'preparateur']
        city:
            groups: ['client', 'location', 'preparateur']
        codePostale:
            groups: ['client', 'location', 'preparateur']
        tel:
            groups: ['client', 'location', 'preparateur']
        client:
            groups: ['location']


AppBundle\Entity\Article:
    attributes:
        id:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        name:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        description:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        price:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        img:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        marque:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        categories:
            groups: ['article', 'categorie', 'client', 'commande', 'basket', 'preparateur']
        basket:
            groups: ['article']  

AppBundle\Entity\Categorie:
    attributes:
        name:
            groups: ['categorie', 'article', 'client', 'commande', 'basket', 'preparateur'] 

AppBundle\Entity\Basket:
    attributes:
        id:
            groups: ['client', 'basket', 'commande', 'article']
        price:
            groups: ['client', 'basket', 'commande', 'article'] 
        delivry:
            groups: ['client', 'basket', 'commande', 'article']
        articles:
            groups: ['client', 'basket', 'commande','preparateur']
        client_parent:
            groups: ['basket', 'commande', 'article', 'preparateur'] 

AppBundle\Entity\Commande:
    attributes:
        id:
            groups: ['client', 'article', 'commande']
        client:
            groups: ['commande', 'preparateur']
        articles:
            groups: ['commande', 'client', 'preparateur']
        preparateur:
            groups: ['commande']
        treatment:
            groups: ['commande', 'client', 'preparateur']
        inDelivring:
            groups: ['commande', 'preparateur']

AppBundle\Entity\Preparateur:
    attributes:
        id:
            groups: ['preparateur']
        name:
            groups: ['preparateur', 'commande']
        mdp:
            groups: ['preparateur']
        commandes:
            groups: ['preparateur']