AppBundle\Entity\Client:
    properties:
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50
AppBundle\Entity\Credentials:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string